[build]
  command = ""
  publish = ""

[[redirects]]
  from = "/*"
  to = "/demo.html"
  status = 200

[[redirects]]
  from = "/demo-mobile.html"
  to = "/demo-mobile.html"
  status = 200

[[redirects]]
  from = "/test.html"
  to = "/test.html"
  status = 200

[[redirects]]
  from = "/404.html"
  to = "/404.html"
  status = 200